### PR TITLE
Feature/restaurant page

### PR DESCRIPTION
**Pull request by NewIncome**
Restaurant-Page project
This project is a basic page of a restaurant with inner tabs controlled with JS

    Factory function for the creation of HTML elements
    Module to make the initial HTML content
    Modules to make the Menu and Contact content
    SCSS file to have determined styles for predefined classes
    An additional module to make the extra feature on-click for the nav links bar

### CODE REVIEW

**Review by Redvanisation — CHANGES_REQUESTED** [review]
# Changes required  ♻️ 

### Hello team  🌟

**Nice work on this project, but the following changes need to be done before moving on ⬇️** 

* [x] The contents of each tab are stored in a `module` in a separated file. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/restaurant_page/tab_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/restaurant-page)).

### _After making the required changes please submit a new code review request_

### Good luck! 🍀

**Comment by NewIncome** [comment]
> # Changes required recycle
> ### Hello team star2
> 
> **Nice work on this project, but the following changes need to be done before moving on arrow_down**
> 
>     * [ ]  The contents of each tab are stored in a `module` in a separated file. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/restaurant_page/tab_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/restaurant-page)).
> 
> 
> ### _After making the required changes please submit a new code review request_
> ### Good luck! four_leaf_clover

Hi @Redvanisation 
Thanks for the review, just a question. It wasn't clear to me.
For that change, I need to do, so I just need to put each tab in a separate file each? Or in the same file, a module for 'content' and a module for 'menu' and that would be ok? Because I believe it is like that, a module for contact and a module for menu are in a separate file and for the home I just call a section of the initial-page module. Or is it that I only need a separate home module in the same tab-pages file?

**Comment by NewIncome** [comment]
Fix pull-request requirement and js file organization:
- Add directory js_assets
- Add home.js file
- Add contact.js file
- Change tab file name to menu, with only menu module
- Move initPageLoad (alias home) module to home file
- Move contact module to contact file
- Move erase module to init-pg-ld file

**Review by Forison — APPROVED** [review]
## Status:: Approved✔️
# 🙋‍♂️ Jose 
### Good job on implementing the changes raised in the previous review. Go ahead and merge the branch and proceed to the next task🤗.
> Whenever you have an issue with a review it is better to send a message to the reviewer via Slack, the reviewer may not see message you post on your pull request.
#### Happy coding👨‍💻
Addo Forison

**Comment by NewIncome** [comment]
> ## Status:: Approvedheavy_check_mark
> # raising_hand_man Jose
> ### Good job on implementing the changes raised in the previous review. Go ahead and merge the branch and proceed to the next taskhugs.
> 
> > Whenever you have an issue with a review it is better to send a message to the reviewer via Slack, the reviewer may not see message you post on your pull request.
> 
> #### Happy codingman_technologist
> 
> Addo Forison

Hi @Forison !
Thank you very much for the answer!!!
Kind regards

**Pull request merged**
